import type { Exercise, WorkoutTemplate } from '@/types/models';

export const seedExercises: Exercise[] = [
  {
    id: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    aliases: ['squat', 'back squat', 'bb squat'],
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['quads', 'glutes'],
    isCompound: true,
    source: 'seed',
  },
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    aliases: ['bench', 'bench press', 'bb bench'],
    category: 'chest',
    equipment: 'barbell',
    primaryMuscles: ['chest', 'triceps'],
    isCompound: true,
    source: 'seed',
  },
  {
    id: 'barbell-deadlift',
    name: 'Barbell Deadlift',
    aliases: ['deadlift', 'pull'],
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['hamstrings', 'glutes', 'back'],
    isCompound: true,
    source: 'seed',
  },
  {
    id: 'barbell-overhead-press',
    name: 'Barbell Overhead Press',
    aliases: ['ohp', 'press', 'shoulder press'],
    category: 'shoulders',
    equipment: 'barbell',
    primaryMuscles: ['shoulders', 'triceps'],
    isCompound: true,
    source: 'seed',
  },
  {
    id: 'pull-up',
    name: 'Pull-Up',
    aliases: ['pullup', 'chin-up'],
    category: 'back',
    equipment: 'bodyweight',
    primaryMuscles: ['lats', 'biceps'],
    isCompound: true,
    source: 'seed',
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    aliases: ['pulldown', 'lat pull'],
    category: 'back',
    equipment: 'cable',
    primaryMuscles: ['lats', 'biceps'],
    isCompound: true,
    source: 'seed',
  },
  {
    id: 'dumbbell-incline-press',
    name: 'Dumbbell Incline Press',
    aliases: ['incline db press', 'incline press'],
    category: 'chest',
    equipment: 'dumbbell',
    primaryMuscles: ['upper chest', 'shoulders'],
    isCompound: true,
    source: 'seed',
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    aliases: ['cable row', 'row'],
    category: 'back',
    equipment: 'cable',
    primaryMuscles: ['mid back', 'lats'],
    isCompound: true,
    source: 'seed',
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    aliases: ['press'],
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['quads', 'glutes'],
    isCompound: true,
    source: 'seed',
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    aliases: ['rdl'],
    category: 'legs',
    equipment: 'barbell',
    primaryMuscles: ['hamstrings', 'glutes'],
    isCompound: true,
    source: 'seed',
  },
  {
    id: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    aliases: ['curl', 'db curl'],
    category: 'arms',
    equipment: 'dumbbell',
    primaryMuscles: ['biceps'],
    isCompound: false,
    source: 'seed',
  },
  {
    id: 'cable-triceps-pressdown',
    name: 'Cable Triceps Pressdown',
    aliases: ['pressdown', 'triceps pushdown'],
    category: 'arms',
    equipment: 'cable',
    primaryMuscles: ['triceps'],
    isCompound: false,
    source: 'seed',
  },
  {
    id: 'machine-leg-curl',
    name: 'Machine Leg Curl',
    aliases: ['leg curl', 'ham curl'],
    category: 'legs',
    equipment: 'machine',
    primaryMuscles: ['hamstrings'],
    isCompound: false,
    source: 'seed',
  },
  {
    id: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    aliases: ['lateral raise', 'side raise'],
    category: 'shoulders',
    equipment: 'dumbbell',
    primaryMuscles: ['side delts'],
    isCompound: false,
    source: 'seed',
  },
  {
    id: 'ab-wheel',
    name: 'Ab Wheel Rollout',
    aliases: ['ab wheel', 'rollout'],
    category: 'core',
    equipment: 'bodyweight',
    primaryMuscles: ['abs'],
    isCompound: false,
    source: 'seed',
  }
];

export const seedTemplates: WorkoutTemplate[] = [
  {
    id: 'tpl-upper-a',
    name: 'Upper A',
    split: 'upper-lower',
    dayLabel: 'Upper',
    exerciseIds: ['barbell-bench-press', 'seated-cable-row', 'barbell-overhead-press', 'lat-pulldown', 'dumbbell-curl', 'cable-triceps-pressdown'],
    source: 'seed',
  },
  {
    id: 'tpl-lower-a',
    name: 'Lower A',
    split: 'upper-lower',
    dayLabel: 'Lower',
    exerciseIds: ['barbell-back-squat', 'romanian-deadlift', 'leg-press', 'machine-leg-curl', 'ab-wheel'],
    source: 'seed',
  },
  {
    id: 'tpl-push-a',
    name: 'Push A',
    split: 'push-pull-legs',
    dayLabel: 'Push',
    exerciseIds: ['barbell-bench-press', 'dumbbell-incline-press', 'barbell-overhead-press', 'dumbbell-lateral-raise', 'cable-triceps-pressdown'],
    source: 'seed',
  },
  {
    id: 'tpl-pull-a',
    name: 'Pull A',
    split: 'push-pull-legs',
    dayLabel: 'Pull',
    exerciseIds: ['barbell-deadlift', 'pull-up', 'seated-cable-row', 'lat-pulldown', 'dumbbell-curl'],
    source: 'seed',
  },
  {
    id: 'tpl-legs-a',
    name: 'Legs A',
    split: 'push-pull-legs',
    dayLabel: 'Legs',
    exerciseIds: ['barbell-back-squat', 'romanian-deadlift', 'leg-press', 'machine-leg-curl', 'ab-wheel'],
    source: 'seed',
  },
  {
    id: 'tpl-full-body-a',
    name: 'Full Body A',
    split: 'full-body',
    dayLabel: 'Full Body',
    exerciseIds: ['barbell-back-squat', 'barbell-bench-press', 'seated-cable-row', 'barbell-overhead-press', 'ab-wheel'],
    source: 'seed',
  },
  {
    id: 'tpl-chest-day',
    name: 'Chest Day',
    split: 'bro-split',
    dayLabel: 'Chest',
    exerciseIds: ['barbell-bench-press', 'dumbbell-incline-press', 'cable-triceps-pressdown'],
    source: 'seed',
  }
];
