-- Daily loop v1: check-ins, habits, stats, and garden unlocks.
-- Safe to re-run.

-- ---------- CHECKINS (v2) ----------
alter table public.checkins
  add column if not exists date date;
alter table public.checkins
  add column if not exists mood_score smallint;
alter table public.checkins
  add column if not exists win_text text;

create unique index if not exists checkins_user_date_key on public.checkins (user_id, date);

-- ---------- HABITS ----------
create table if not exists public.habits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint habits_title_nonempty check (char_length(title) > 0)
);

drop trigger if exists habits_set_updated_at on public.habits;
create trigger habits_set_updated_at
before update on public.habits
for each row execute function public.set_updated_at();

create unique index if not exists habits_user_title_key on public.habits (user_id, title);

-- ---------- HABIT COMPLETIONS ----------
create table if not exists public.habit_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  habit_id bigint not null references public.habits(id) on delete cascade,
  date date not null,
  completed boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists habit_completions_set_updated_at on public.habit_completions;
create trigger habit_completions_set_updated_at
before update on public.habit_completions
for each row execute function public.set_updated_at();

create unique index if not exists habit_completions_user_habit_date_key
  on public.habit_completions (user_id, habit_id, date);

-- ---------- USER STATS ----------
create table if not exists public.user_stats (
  user_id uuid primary key references auth.users(id) on delete cascade,
  streak integer not null default 0,
  last_completed_date date,
  pet_mood_state text not null default 'neutral',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists user_stats_set_updated_at on public.user_stats;
create trigger user_stats_set_updated_at
before update on public.user_stats
for each row execute function public.set_updated_at();

-- ---------- GARDEN ITEMS ----------
create table if not exists public.garden_items (
  id bigint generated by default as identity primary key,
  name text not null,
  tier integer not null default 1,
  created_at timestamptz not null default now()
);

create unique index if not exists garden_items_name_key on public.garden_items (name);

insert into public.garden_items (name, tier)
values
  ('Tiny Sprout', 1),
  ('Soft Pebble', 1),
  ('Glow Lantern', 2),
  ('Story Stone', 2),
  ('Little Arch', 3)
on conflict (name) do nothing;

-- ---------- GARDEN UNLOCKS ----------
create table if not exists public.garden_unlocks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id bigint not null references public.garden_items(id) on delete cascade,
  streak_at_unlock integer,
  unlocked_at timestamptz not null default now()
);

create unique index if not exists garden_unlocks_user_item_key
  on public.garden_unlocks (user_id, item_id);
alter table public.garden_unlocks
  add column if not exists streak_at_unlock integer;

-- ---------- RLS ----------
alter table public.habits enable row level security;
alter table public.habit_completions enable row level security;
alter table public.user_stats enable row level security;
alter table public.garden_unlocks enable row level security;

-- allow reads of base items to all authenticated users (no user_id column)
alter table public.garden_items enable row level security;
drop policy if exists garden_items_read_all on public.garden_items;
create policy garden_items_read_all on public.garden_items
  for select using (true);

-- Checkins (replace older policies to include new columns)
drop policy if exists checkins_select_own on public.checkins;
drop policy if exists checkins_insert_own on public.checkins;
drop policy if exists checkins_update_own on public.checkins;
drop policy if exists checkins_delete_own on public.checkins;

create policy checkins_select_own on public.checkins for select using (auth.uid() = user_id);
create policy checkins_insert_own on public.checkins for insert with check (auth.uid() = user_id);
create policy checkins_update_own on public.checkins for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy checkins_delete_own on public.checkins for delete using (auth.uid() = user_id);

-- Habits
drop policy if exists habits_select_own on public.habits;
drop policy if exists habits_insert_own on public.habits;
drop policy if exists habits_update_own on public.habits;
drop policy if exists habits_delete_own on public.habits;

create policy habits_select_own on public.habits for select using (auth.uid() = user_id);
create policy habits_insert_own on public.habits for insert with check (auth.uid() = user_id);
create policy habits_update_own on public.habits for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy habits_delete_own on public.habits for delete using (auth.uid() = user_id);

-- Habit completions
drop policy if exists habit_completions_select_own on public.habit_completions;
drop policy if exists habit_completions_insert_own on public.habit_completions;
drop policy if exists habit_completions_update_own on public.habit_completions;
drop policy if exists habit_completions_delete_own on public.habit_completions;

create policy habit_completions_select_own on public.habit_completions
  for select using (auth.uid() = user_id);
create policy habit_completions_insert_own on public.habit_completions
  for insert with check (auth.uid() = user_id);
create policy habit_completions_update_own on public.habit_completions
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy habit_completions_delete_own on public.habit_completions
  for delete using (auth.uid() = user_id);

-- User stats
drop policy if exists user_stats_select_own on public.user_stats;
drop policy if exists user_stats_insert_own on public.user_stats;
drop policy if exists user_stats_update_own on public.user_stats;
drop policy if exists user_stats_delete_own on public.user_stats;

create policy user_stats_select_own on public.user_stats for select using (auth.uid() = user_id);
create policy user_stats_insert_own on public.user_stats for insert with check (auth.uid() = user_id);
create policy user_stats_update_own on public.user_stats for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy user_stats_delete_own on public.user_stats for delete using (auth.uid() = user_id);

-- Garden unlocks
drop policy if exists garden_unlocks_select_own on public.garden_unlocks;
drop policy if exists garden_unlocks_insert_own on public.garden_unlocks;
drop policy if exists garden_unlocks_update_own on public.garden_unlocks;
drop policy if exists garden_unlocks_delete_own on public.garden_unlocks;

create policy garden_unlocks_select_own on public.garden_unlocks
  for select using (auth.uid() = user_id);
create policy garden_unlocks_insert_own on public.garden_unlocks
  for insert with check (auth.uid() = user_id);
create policy garden_unlocks_update_own on public.garden_unlocks
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy garden_unlocks_delete_own on public.garden_unlocks
  for delete using (auth.uid() = user_id);
