create table if not exists public.garden_plants (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  plant_type text not null default 'flower',
  stage text not null default 'seeded',
  planted_at timestamptz not null default now(),
  last_watered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.garden_plants drop constraint if exists garden_plants_stage_check;
alter table public.garden_plants
  add constraint garden_plants_stage_check check (stage in ('seeded', 'sprout', 'bloomed'));

drop trigger if exists garden_plants_set_updated_at on public.garden_plants;
create trigger garden_plants_set_updated_at
before update on public.garden_plants
for each row execute function public.set_updated_at();

create unique index if not exists garden_plants_user_id_plant_type_key
  on public.garden_plants (user_id, plant_type);
create index if not exists garden_plants_user_id_idx
  on public.garden_plants (user_id);

alter table public.garden_plants enable row level security;

drop policy if exists garden_plants_select_own on public.garden_plants;
create policy garden_plants_select_own on public.garden_plants
  for select using (auth.uid() = user_id);
drop policy if exists garden_plants_insert_own on public.garden_plants;
create policy garden_plants_insert_own on public.garden_plants
  for insert with check (auth.uid() = user_id);
drop policy if exists garden_plants_update_own on public.garden_plants;
create policy garden_plants_update_own on public.garden_plants
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists garden_plants_delete_own on public.garden_plants;
create policy garden_plants_delete_own on public.garden_plants
  for delete using (auth.uid() = user_id);
