-- Tasks + completions for Daily Tasks screen.
-- Requires: public.set_updated_at() function already defined in schema_mvp.sql

-- ---------- TASKS ----------
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Make re-runs safe
drop trigger if exists tasks_set_updated_at on public.tasks;

create trigger tasks_set_updated_at
before update on public.tasks
for each row execute function public.set_updated_at();

-- ---------- TASK COMPLETIONS ----------
create table if not exists public.task_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  task_id bigint not null references public.tasks(id) on delete cascade,
  completion_date date not null,
  done boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Make re-runs safe
drop trigger if exists task_completions_set_updated_at on public.task_completions;

create trigger task_completions_set_updated_at
before update on public.task_completions
for each row execute function public.set_updated_at();

create unique index if not exists task_completions_user_task_date_key
  on public.task_completions (user_id, task_id, completion_date);

-- ---------- RLS ----------
alter table public.tasks enable row level security;
alter table public.task_completions enable row level security;

-- Make policy re-runs safe
drop policy if exists tasks_select_own on public.tasks;
drop policy if exists tasks_insert_own on public.tasks;
drop policy if exists tasks_update_own on public.tasks;
drop policy if exists tasks_delete_own on public.tasks;

drop policy if exists task_completions_select_own on public.task_completions;
drop policy if exists task_completions_insert_own on public.task_completions;
drop policy if exists task_completions_update_own on public.task_completions;
drop policy if exists task_completions_delete_own on public.task_completions;

create policy tasks_select_own on public.tasks
  for select using (auth.uid() = user_id);

create policy tasks_insert_own on public.tasks
  for insert with check (auth.uid() = user_id);

create policy tasks_update_own on public.tasks
  for update using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy tasks_delete_own on public.tasks
  for delete using (auth.uid() = user_id);

create policy task_completions_select_own on public.task_completions
  for select using (auth.uid() = user_id);

create policy task_completions_insert_own on public.task_completions
  for insert with check (auth.uid() = user_id);

create policy task_completions_update_own on public.task_completions
  for update using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy task_completions_delete_own on public.task_completions
  for delete using (auth.uid() = user_id);
