import type { ImageSourcePropType } from "react-native";
import type { PlantStage, ScenePoint } from "../../domain/gardenScene";

// Generated by scripts/build-garden-scene.js from the painted background (assets/garden.png).
// scene.json and the sprites must be regenerated together; never edit them by hand.
const scene = require("../../../assets/garden/scene/scene.json") as {
  image: { width: number; height: number };
  spots: Array<ScenePoint & { scale?: number }>;
  pet: ScenePoint & { heightRatio: number };
  sprites: Record<PlantStage, { width: number; height: number; anchorX: number; anchorY: number }>;
};

export const SCENE = scene;

export const SCENE_BACKGROUND: ImageSourcePropType = require("../../../assets/garden/scene/garden_bg.jpg");

// Metro needs static require() calls, so the stage -> sprite map is spelled out.
export const PLANT_SPRITES: Record<PlantStage, ImageSourcePropType> = {
  seed: require("../../../assets/garden/scene/patch_seed.png"),
  sproutSmall: require("../../../assets/garden/scene/patch_sproutSmall.png"),
  sprout: require("../../../assets/garden/scene/patch_sprout.png"),
  bloom: require("../../../assets/garden/scene/patch_bloom.png"),
};

/** How the painting is framed in each place it appears: what to centre on and how far to zoom in. */
export const SCENE_FRAMING = {
  home: { focus: { u: 0.56, v: 0.7 }, zoom: 1.3 },
  garden: { focus: { u: 0.56, v: 0.69 }, zoom: 1.22 },
  /** the Pet tab: close on the pet, the patch just in view on the right */
  pet: { focus: { u: 0.44, v: 0.72 }, zoom: 1.45 },
  /** onboarding: the empty patch and the spot the pet will take */
  welcome: { focus: { u: 0.5, v: 0.72 }, zoom: 1.35 },
} as const;

export type SceneVariant = keyof typeof SCENE_FRAMING;
