-- GENERATED by local-backend/build-migrations.js. Do not edit; edit the source and re-run.
-- source: supabase/migrations/2025_12_31_stabilize_schema.sql
-- sha256: 49868140e3634b96942b3c8cb8ba433433af95b576b1360434a55d577bf105b4

-- Stabilize schema for checkins, habits, completions, stats, and garden unlocks.

-- CHECKINS: add columns and backfill
alter table public.checkins add column if not exists date date;
alter table public.checkins add column if not exists mood_score integer;
alter table public.checkins add column if not exists win_text text;

update public.checkins set date = coalesce(date, created_at::date) where date is null;
do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'checkins' and column_name = 'note') then
    update public.checkins set win_text = coalesce(win_text, note) where win_text is null;
  end if;
end$$;

-- dedupe checkins by (user_id, date), keep latest created_at
delete from public.checkins a
using public.checkins b
where a.user_id = b.user_id
  and a.date = b.date
  and a.ctid < b.ctid
  and a.created_at <= b.created_at;

create unique index if not exists checkins_user_date_idx on public.checkins (user_id, date);

-- HABITS: ensure user_id exists (per-user model)
alter table public.habits add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.habits add column if not exists active boolean default true;
alter table public.habits add column if not exists title text;
alter table public.habits add column if not exists sort_order integer default 0;
create unique index if not exists habits_user_title_key on public.habits (user_id, title);

alter table public.habits enable row level security;
drop policy if exists habits_select_own on public.habits;
drop policy if exists habits_insert_own on public.habits;
drop policy if exists habits_update_own on public.habits;
drop policy if exists habits_delete_own on public.habits;
create policy habits_select_own on public.habits for select using (auth.uid() = user_id);
create policy habits_insert_own on public.habits for insert with check (auth.uid() = user_id);
create policy habits_update_own on public.habits for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy habits_delete_own on public.habits for delete using (auth.uid() = user_id);

-- HABIT COMPLETIONS
create table if not exists public.habit_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  habit_id bigint not null references public.habits(id) on delete cascade,
  date date not null,
  completed boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists habit_completions_user_habit_date_key on public.habit_completions (user_id, habit_id, date);
alter table public.habit_completions enable row level security;
drop policy if exists habit_completions_select_own on public.habit_completions;
drop policy if exists habit_completions_insert_own on public.habit_completions;
drop policy if exists habit_completions_update_own on public.habit_completions;
drop policy if exists habit_completions_delete_own on public.habit_completions;
create policy habit_completions_select_own on public.habit_completions for select using (auth.uid() = user_id);
create policy habit_completions_insert_own on public.habit_completions for insert with check (auth.uid() = user_id);
create policy habit_completions_update_own on public.habit_completions for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy habit_completions_delete_own on public.habit_completions for delete using (auth.uid() = user_id);

-- USER STATS
create table if not exists public.user_stats (
  user_id uuid primary key references auth.users(id) on delete cascade,
  streak integer not null default 0,
  last_completed_date date,
  pet_mood_state text not null default 'neutral',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.user_stats enable row level security;
drop policy if exists user_stats_select_own on public.user_stats;
drop policy if exists user_stats_insert_own on public.user_stats;
drop policy if exists user_stats_update_own on public.user_stats;
drop policy if exists user_stats_delete_own on public.user_stats;
create policy user_stats_select_own on public.user_stats for select using (auth.uid() = user_id);
create policy user_stats_insert_own on public.user_stats for insert with check (auth.uid() = user_id);
create policy user_stats_update_own on public.user_stats for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy user_stats_delete_own on public.user_stats for delete using (auth.uid() = user_id);

-- GARDEN UNLOCKS
alter table public.garden_unlocks add column if not exists streak_at_unlock integer;
create unique index if not exists garden_unlocks_user_item_key on public.garden_unlocks (user_id, item_id);
