-- GENERATED by local-backend/build-migrations.js. Do not edit; edit the source and re-run.
-- source: supabase/schema_mvp.sql
-- sha256: 89a059b841537e71aafcc70bc553441fdbca007f9a0d792651eb46ef03f69429

-- Minimal MVP schema for Supabase-only app.

create extension if not exists "pgcrypto";

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  pet_photo_url text,
  streak_count integer not null default 0,
  xp integer not null default 0,
  garden_level integer not null default 1,
  last_checkin_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create table if not exists public.pet (
  user_id uuid primary key references auth.users(id) on delete cascade,
  name text,
  state text not null default 'idle',
  level integer not null default 1,
  photo_url text,
  stylized_url text,
  cutout_url text,
  mask_url text,
  processing_status text not null default 'idle',
  processing_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger pet_set_updated_at
before update on public.pet
for each row execute function public.set_updated_at();

create table if not exists public.checkins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  checkin_date date not null,
  mood integer,
  note text,
  created_at timestamptz not null default now()
);

create unique index if not exists checkins_user_id_checkin_date_key
  on public.checkins (user_id, checkin_date);

alter table public.profiles enable row level security;
alter table public.pet enable row level security;
alter table public.checkins enable row level security;

create policy profiles_select_own on public.profiles
  for select using (auth.uid() = user_id);
create policy profiles_insert_own on public.profiles
  for insert with check (auth.uid() = user_id);
create policy profiles_update_own on public.profiles
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy profiles_delete_own on public.profiles
  for delete using (auth.uid() = user_id);

create policy pet_select_own on public.pet
  for select using (auth.uid() = user_id);
create policy pet_insert_own on public.pet
  for insert with check (auth.uid() = user_id);
create policy pet_update_own on public.pet
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy pet_delete_own on public.pet
  for delete using (auth.uid() = user_id);

create policy checkins_select_own on public.checkins
  for select using (auth.uid() = user_id);
create policy checkins_insert_own on public.checkins
  for insert with check (auth.uid() = user_id);
create policy checkins_update_own on public.checkins
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy checkins_delete_own on public.checkins
  for delete using (auth.uid() = user_id);
