-- GENERATED by local-backend/build-migrations.js. Do not edit; edit the source and re-run.
-- source: local-backend/sql/pin_function_search_path.sql
-- sha256: 3b5391ea383d689e5831327eba04b5614a772069952465098a9f4e6dc50a6ce1

-- Supabase lint 0011: pin search_path on the remaining helper functions.
-- Applied to Bloom on 2026-10-02 as migration 20261002014442_pin_function_search_path.
alter function public.set_updated_at() set search_path = public;
alter function public.seed_default_tasks() set search_path = public;
alter function public.clamp_local_day(date, timestamptz) set search_path = public;
alter function public.clamp_client_instant(timestamptz) set search_path = public;
