-- GENERATED by local-backend/build-migrations.js. Do not edit; edit the source and re-run.
-- source: supabase/migrations/2026_02_05_pet_processing_status.sql
-- sha256: 0b0bec706b3500b1a47682f7e5aa569942eadba4414063b271ecec683603af0e

-- Add pet processing status + asset URLs
alter table public.pet
  add column if not exists stylized_url text,
  add column if not exists cutout_url text,
  add column if not exists mask_url text,
  add column if not exists processing_status text not null default 'idle',
  add column if not exists processing_error text,
  add column if not exists updated_at timestamptz not null default now();
