-- GENERATED by local-backend/build-migrations.js. Do not edit; edit the source and re-run.
-- source: local-backend/sql/pets_bucket_private.sql
-- sha256: efe876d389cef949cc25ae485552ee5549a1498e12da09782614cb473650cbc0

-- Forward migration (2026-09-27): the pet photo bucket becomes private, one folder per user.
-- Source: docs/backend/STAGING_PLAN.md P1 #6 (R-13, R-14).
--
-- Before: `pets` was public, so every object (including the real photo at original/<uid>.<ext>) was
-- readable by anyone holding its URL; the 1-year signed URL the client stored protected nothing.
-- After: private bucket; every object lives under the owner's user id as the first path segment:
--   <uid>/original.<ext>                   the photo the person picked
--   <uid>/processed/{stylized,cutout,mask}.png   the optional painted portrait (pet-stylize)
-- The client stores token-free locator URLs and asks for a short-lived signed URL when it shows an image
-- (src/services/petPhotoUrls.ts). Edge Functions use the service role and are not limited by these policies.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('pets', 'pets', false, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif'])
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

-- the old policies matched original/<uid>.* and processed/<uid>/*
drop policy if exists "pets_select_own" on storage.objects;
drop policy if exists "pets_insert_own" on storage.objects;
drop policy if exists "pets_update_own" on storage.objects;
drop policy if exists "pets_delete_own" on storage.objects;

drop policy if exists "pets_owner_select" on storage.objects;
create policy "pets_owner_select" on storage.objects
  for select to authenticated
  using (bucket_id = 'pets' and (storage.foldername(name))[1] = (select auth.uid())::text);

drop policy if exists "pets_owner_insert" on storage.objects;
create policy "pets_owner_insert" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'pets' and (storage.foldername(name))[1] = (select auth.uid())::text);

drop policy if exists "pets_owner_update" on storage.objects;
create policy "pets_owner_update" on storage.objects
  for update to authenticated
  using (bucket_id = 'pets' and (storage.foldername(name))[1] = (select auth.uid())::text)
  with check (bucket_id = 'pets' and (storage.foldername(name))[1] = (select auth.uid())::text);

drop policy if exists "pets_owner_delete" on storage.objects;
create policy "pets_owner_delete" on storage.objects
  for delete to authenticated
  using (bucket_id = 'pets' and (storage.foldername(name))[1] = (select auth.uid())::text);
