-- GENERATED by local-backend/build-migrations.js. Do not edit; edit the source and re-run.
-- source: supabase/migrations/2026_01_02_habits_created_at.sql
-- sha256: 3f2f722eb7a222281a753260caab5c83fcbd6b0c84854d174d2d5051edaa3a67

alter table public.habits
  add column if not exists created_at timestamptz;

update public.habits
  set created_at = now()
  where created_at is null;

alter table public.habits
  alter column created_at set default now(),
  alter column created_at set not null;
