-- Daily loop schema fix (ALTER-only to match runtime expectations).

-- ---------- CHECKINS ----------
alter table public.checkins
  add column if not exists date date;
alter table public.checkins
  add column if not exists mood_score integer;
alter table public.checkins
  add column if not exists win_text text;

-- backfill date from existing columns
update public.checkins
set date = coalesce(date, checkin_date, created_at::date)
where date is null;

-- migrate note -> win_text if present
do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'checkins' and column_name = 'note') then
    update public.checkins set win_text = coalesce(win_text, note);
  end if;
end$$;

create unique index if not exists checkins_user_date_idx on public.checkins (user_id, date);

-- RLS (idempotent)
alter table public.checkins enable row level security;
drop policy if exists checkins_select_own on public.checkins;
drop policy if exists checkins_insert_own on public.checkins;
drop policy if exists checkins_update_own on public.checkins;
drop policy if exists checkins_delete_own on public.checkins;

create policy checkins_select_own on public.checkins for select using (auth.uid() = user_id);
create policy checkins_insert_own on public.checkins for insert with check (auth.uid() = user_id);
create policy checkins_update_own on public.checkins for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy checkins_delete_own on public.checkins for delete using (auth.uid() = user_id);

-- ---------- HABITS ----------
-- If habits table exists without user_id, add it (nullable to avoid failing existing rows).
alter table public.habits
  add column if not exists user_id uuid references auth.users(id);
alter table public.habits
  add column if not exists title text;
alter table public.habits
  add column if not exists active boolean default true;

create unique index if not exists habits_user_title_key on public.habits (user_id, title) where user_id is not null;

-- RLS for per-user habits
alter table public.habits enable row level security;
drop policy if exists habits_select_own on public.habits;
drop policy if exists habits_insert_own on public.habits;
drop policy if exists habits_update_own on public.habits;
drop policy if exists habits_delete_own on public.habits;

create policy habits_select_own on public.habits for select using (auth.uid() = user_id);
create policy habits_insert_own on public.habits for insert with check (auth.uid() = user_id);
create policy habits_update_own on public.habits for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy habits_delete_own on public.habits for delete using (auth.uid() = user_id);

-- ---------- HABIT COMPLETIONS ----------
create table if not exists public.habit_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  habit_id bigint not null references public.habits(id) on delete cascade,
  date date not null,
  completed boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists habit_completions_user_habit_date_key on public.habit_completions (user_id, habit_id, date);

alter table public.habit_completions enable row level security;
drop policy if exists habit_completions_select_own on public.habit_completions;
drop policy if exists habit_completions_insert_own on public.habit_completions;
drop policy if exists habit_completions_update_own on public.habit_completions;
drop policy if exists habit_completions_delete_own on public.habit_completions;

create policy habit_completions_select_own on public.habit_completions for select using (auth.uid() = user_id);
create policy habit_completions_insert_own on public.habit_completions for insert with check (auth.uid() = user_id);
create policy habit_completions_update_own on public.habit_completions for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy habit_completions_delete_own on public.habit_completions for delete using (auth.uid() = user_id);

-- ---------- USER STATS ----------
create table if not exists public.user_stats (
  user_id uuid primary key references auth.users(id) on delete cascade,
  streak integer not null default 0,
  last_completed_date date,
  pet_mood_state text not null default 'neutral',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_stats enable row level security;
drop policy if exists user_stats_select_own on public.user_stats;
drop policy if exists user_stats_insert_own on public.user_stats;
drop policy if exists user_stats_update_own on public.user_stats;
drop policy if exists user_stats_delete_own on public.user_stats;

create policy user_stats_select_own on public.user_stats for select using (auth.uid() = user_id);
create policy user_stats_insert_own on public.user_stats for insert with check (auth.uid() = user_id);
create policy user_stats_update_own on public.user_stats for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy user_stats_delete_own on public.user_stats for delete using (auth.uid() = user_id);

-- ---------- GARDEN ITEMS / UNLOCKS ----------
alter table public.garden_unlocks
  add column if not exists streak_at_unlock integer;

-- base items table (if absent)
create table if not exists public.garden_items (
  id bigint generated by default as identity primary key,
  name text not null,
  tier integer not null default 1,
  created_at timestamptz not null default now()
);
create unique index if not exists garden_items_name_key on public.garden_items (name);

-- unlocks table (if absent)
create table if not exists public.garden_unlocks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id bigint not null references public.garden_items(id) on delete cascade,
  streak_at_unlock integer,
  unlocked_at timestamptz not null default now()
);
create unique index if not exists garden_unlocks_user_item_key on public.garden_unlocks (user_id, item_id);

alter table public.garden_items enable row level security;
alter table public.garden_unlocks enable row level security;

drop policy if exists garden_items_read_all on public.garden_items;
create policy garden_items_read_all on public.garden_items for select using (true);

drop policy if exists garden_unlocks_select_own on public.garden_unlocks;
drop policy if exists garden_unlocks_insert_own on public.garden_unlocks;
drop policy if exists garden_unlocks_update_own on public.garden_unlocks;
drop policy if exists garden_unlocks_delete_own on public.garden_unlocks;

create policy garden_unlocks_select_own on public.garden_unlocks for select using (auth.uid() = user_id);
create policy garden_unlocks_insert_own on public.garden_unlocks for insert with check (auth.uid() = user_id);
create policy garden_unlocks_update_own on public.garden_unlocks for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy garden_unlocks_delete_own on public.garden_unlocks for delete using (auth.uid() = user_id);

-- seed garden items (idempotent)
insert into public.garden_items (name, tier)
values ('Tiny Sprout', 1), ('Soft Pebble', 1), ('Glow Lantern', 2), ('Story Stone', 2), ('Little Arch', 3)
on conflict (name) do nothing;
